module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    ADMIN_EMAIL:'thomas@gmail.com',
    ADMIN_PASS:'000',
    ADMIN_NAME:'thoma'
}